# Generated by Django 3.2.21 on 2023-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aslmodel',
            name='configmap',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
